baseURL = 'https://sethur.de/'
languageCode = 'de-de'
title = 'Willkommen auf meiner Website'
theme = "hugo-theme-m10c"

[params]
author = "Sethur"
description = "Nico aus dem Sauerland, Jahrgang 1990, lebt für IT und Gaming. Fasziniert von LKW-Technik und Hydroponik, teilt er auf seiner Webseite Erfahrungen und Wissen. Willkommen auf seiner Seite der Leidenschaften und Erkenntnisse!"

[[menu.main]]
idetifier = "posts"
name = "Blog"
url = "/posts/"